### ISSUE TITLE
Spec - Define equality handling with arrays and subdocs

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#109]
This is for `{'foo' : "bar"}` filters and  `{'foo' : {"$eq" : "bar"}}` which was implemented in #42 - they are the same. 

Spec should say: 

For query `{'foo' : "bar"}` this matches: 
- foo as a string with value bar 
- foo is an array that contains atleast one item that is the string "bar", the length of the array is not important.

For the query `{'foo' : ["bar"]}` this:
- matches foo as an array that is exactly `["bar"]`
- DOES not support sub arrays, so does not match foo == `[ ["bar"], "baz"]`

Not, this is NOT a reflexive operation - i.e. if the RHS operand is a string (or other value) we will match against a field of that type or field with an array item of that type. However if the RHS operand is an array we only match against fields that are arrays. 

this spec work is to catchup with 
#107 
#106 
#96 - may need to re-work if we have a single indexes field for all equality operations. 
#89  - check if this needs re-work, we can put the all the paths for equality into one CQL set

**Comment by tatu-at-datastax** [comment]
@vkarpov15 Correct, immediate nesting won't work (and we wouldn't/couldn't support it anyway).

What I am not 100% sure about is mixture of sub-doc/array nesting like:

```
{ 'orders' : [
   { 'id' : 'order1',
     'lineItems' : [{
         'id' : 'lineitem1',
         'count': 5
     }]
   }
]}
```

and then expect to use

```
{ `orders.lineitems.count` : { `$eq` : 5 }}
```

instead of having to specify all but last array's index:

```
{ `orders.0.lineitems.count` : { `$eq` : 5 }}
```

which I am afraid might actually work with Mongo, but not for us.
If it doesn't work with Mongo that'd be great

**Comment by vkarpov15** [comment]
@tatu-at-datastax looks like that particular syntax doesn't work:

```
MongoDB Enterprise > db.tests.insertOne({ 'orders' : [
...    { 'id' : 'order1',
...      'lineItems' : [{
...          'id' : 'lineitem1',
...          'count': 5
...      }]
...    }
... ]})
{
	"acknowledged" : true,
	"insertedId" : ObjectId("63ee94a32ba8deac98145cd5")
}
MongoDB Enterprise > db.tests.findOne({ 'orders.0.lineitems.count' : { $eq : 5 }})
null
MongoDB Enterprise > db.tests.findOne({ 'orders.0.lineitems.count' : 5 })
null
MongoDB Enterprise > 
```

I'm not surprised. In my experience, MongoDB gives up on drilling into nested arrays, even if you have an array in a subdocument array. I think it's safe to assume that handling nested arrays is not something we need to do.

**Comment by tatu-at-datastax** [comment]
@vkarpov15 Ok thank you for verifying this! This is good news and yes, makes sense; handling multiple levels of nesting this way would get pretty expensive (and likely useless from user POV as well).

**Comment by amorton** [comment]
> { 'foo.bar': 'baz' } matches { foo: [{ bar: 'baz' }] }, does not match { foo: [[{ bar: 'baz' }]] }

@tatu-at-datastax or @vkarpov15  can we confirm if the `{ 'foo.bar': 'baz' } matches { foo: [{ bar: 'baz' }] }` is supported ? This looks lot like `$elemMatch`, I was trying to avoid array filtering like that as we could not push it down to the DB (yet)

**Comment by vkarpov15** [comment]
@amorton `$elemMatch` is related, but slightly different. The difference is when you have multiple clauses that reference an array. `{ 'foo.bar': 1, 'foo.baz': 2 }` will match `{ foo: [{ bar: 1 }, { baz: 2 }] }`, because `foo` has at least 1 element that matches `bar: 1` and at least 1 element that matches `baz: 2`.

But `{ foo: { $elemMatch: { bar: 1, baz: 2 } } }` will not match  `{ foo: [{ bar: 1 }, { baz: 2 }] }`. Because `$elemMatch` means 1 element must match both `{ bar: 1 }` and `{ baz: 2 }`.

It doesn't look like `foo.bar: 'baz'` currently works in Stargate. We shouldn't need this for demo purposes.

**Comment by tatu-at-datastax** [comment]
@amorton yes, what @vkarpov15 said. You are correct in that first array matches, and second (nested) will not.
This is because in second case `arrayContains` will have index segment in key, so instead of being for property `foo`, it will be for `foo.0`. It can be found, but only if looking for 

```
{ 'foo.0.bar' : 'baz' }
```
