### ISSUE TITLE
Change sort clause format

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#323]
Implement sort clause to be json document { "active_user" : -1 } where 1 represent ascending and -1 represent descending order.

**Comment by maheshrajamani** [comment]
@amorton Can you opine on this change? Val suggested to use json object representation for sort clause, but the spec has it  as array of text. Do we need to change this?

**Comment by tatu-at-datastax** [comment]
One interesting thing here is that use of JSON Objects for sort criteria requires order-preservation in JSON -- something that logically JSON does not do. It's not a problem for us since JSON library (Jackson) explicitly retains order (reading and writing), but good to note still.

I think I agree that it is good to be compatible with other backends Mongoose supports (and has before Stargate JSON API).
May make it easier for other client libraries/frameworks to integrate with JSON API.

**Comment by amorton** [comment]
> @amorton Can you opine on this change? Val suggested to use json object representation for sort clause, but the spec has it as array of text. Do we need to change this?

You are correct, and ahead of me. It should be the map as you have in the example, and yes check with Val. This way is more compatible with mongoose. 

> One interesting thing here is that use of JSON Objects for sort criteria requires order-preservation in JSON -- something that logically JSON does not do. It's not a problem for us since JSON library (Jackson) explicitly retains order (reading and writing), but good to note still.

This is why the original spec used a list, I was rebelling against the idea of relying on the order of a the JSOn doc. But we have done that in so many other places I dont think it is much of an issue now.

**Comment by vkarpov15** [comment]
`{ sortKey1: 1, sortKey2: 1 }` is more compatible with Mongoose, and the problem with using `['-sortKey1']` is that means fields can't start with `-`.

Mongoose does support using `-sortKey1` syntax, but there is an alternative just in case someone is using a field with `-` in the name.

Re: ordering, @tatu-at-datastax is right that JSON explicitly doesn't guarantee key order, object keys are unordered. This has always been a bit of an odd point in JavaScript - JavaScript _does_ ensure object key order since ES2015, but apparently JSON does not.

If JSON spec compliance is important, we can also support the following syntax: `[['sortKey1', 1], ['sortKey2', 2]]`. This syntax is sufficiently common in JavaScript because of the [`Object.entries()` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries), and does ensure order.

**Comment by tatu-at-datastax** [comment]
@vkarpov15 FwTW, JSON library we use (Jackson) fully preserves ordering during its processing (including using order-preserving `LinkedHashMap` for `Map`-valued POJO properties) so this is not a practical issue. More a conceptual sidenote.

So I think we'll go with simple JSON Object notation for now; as long as clients can specify ordering of Object entries for requests they should be fine. And if not, cross that bridge then with alt formats as necessary.
