### ISSUE TITLE
Add first-class support for Date-Time values for JSON-API

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#362]
Currently we support a subset of datatypes Mongoose supports, basically matching native JSON types (Objects/sub-docs, Arrays, Number, Strings, Booleans, null), and one pseudo-type (Doc Id).

It would make sense to also support Date/Time, so users need not handle conversion to/from JSON String or Number types, but can use native Javascript Date type (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) on client-side and get it efficiently handled on JSON API server side.

Current thinking is to convention defined by EJSON (https://docs.meteor.com/api/ejson.html), in which numeric (milliseconds since 1.1.1970 timestamp, standard used by Java and Javascript as well as many other platforms) is encapsulates as a single-entry JSON Object like:

```
{ "$date": 1358205756553 }
```

This allows for reliable auto-detection because JSON API Object/sub-doc properties can not start with `$` character.

Details of this approach will be added here and after/during prototyping Spec needs to be updated. We will also file separate issues for different parts of handling; so tasks include:

* Update Spec to describe storage and logic
* Create new index field for Date/Time values, update hashing, shredder (#370)
* Change Insert and Update operation to update timestamp index column (#378)
* Change doc-id (`_id`) handling to recognize and support new id type (#371)
* Test that (and change if need be) update operators work with Date/Time values (#372)
* Test that (and change if necessary) Projection works with Date/Time values (#373)
* Change in-memory sort to auto-detect and convert Date/Time values appropriately for sorting (#374)
* Change query filters to auto-detect and convert Date/Time values appropriately for equality queries (#375)
* Add support for `$currentDate` update operation (#397)

**Comment by vkarpov15** [comment]
Just a couple of details to confirm:

1. Mongoose only has one Date type that corresponds to a Date in JavaScript and a [Date in MongoDB](https://www.mongodb.com/docs/manual/reference/bson-types/#date). Mongoose doesn't have first class support for [MongoDB's internal timestamp type](https://www.mongodb.com/docs/manual/reference/bson-types/#timestamps).
2. Mongoose does not expect timezone information to be stored with the date. Dates are 64 bit ints in MongoDB.
3. There are no special query operators for dates. However, `$eq`, `$in`, `$lt`, `$lte`, `$gt`, and `$gte` all work on dates. In particular, `myDate: { $gt: new Date() }` gives you all documents where the `myDate` property is _after_ right now.
4. There is one special update operator for dates: [$currentDate](https://www.mongodb.com/docs/manual/reference/operator/update/currentDate/). That sets a property to the current date. In my experience, $currentDate is rarely used because it is easy to simply set a date to the current date.

**Comment by tatu-at-datastax** [comment]
@vkarpov15 Excellent -- thank you confirming. This aligns with our understanding of things, plans (only supporting `Date`, not `Timestamp`; storage as 64-bit milliseconds since epoch; no special operators aside from `$currentDate` (which may be added but is not super popular)).

**Comment by tatu-at-datastax** [comment]
All sub-tasks completed, Date-Time type support considered complete.
