### ISSUE TITLE
Write EPIPE error while inserting doc over 1 MB

### ISSUE THREAD

**Issue by kathirsvn** [stargate/jsonapi#442]
While trying to insert a document with size greater than 1MB, the server is expected to return below message in the `errors` field in the response.

```json
[{"message":"Request failed with status code 413"}]
```

But instead of the above, intermittently, we get back error message as `write EPIPE`, which the stargate-mongoose CI tests fail intermittently (attached the logs from one of the failed runs)
[stargate_mongoose_ci_fail_logs.txt](https://github.com/stargate/jsonapi/files/11619106/stargate_mongoose_ci_fail_logs.txt)
.

```json
[{"message":"write EPIPE"}]
```

Request (document with size 1 MB):
```json
insertOne: {
    document: {
      username: 'aaaaaaaa'... 1048566 more characters
    }
  }
}
```

**Comment by tatu-at-datastax** [comment]
@kathirsvn The underlying problem is probably due to Quarkus forcibly shutting down connection on 1 MB limit, and that sometimes leading to client-side not getting response. I am not sure how this could be directly changed, however, what I think makes sense is to increase this low-level limit so that:

1. It only gets hit by significantly bigger request payloads (f.ex 10 megs) to protected against very likely malicious
2. Stricter limit applied by existing document validation (in `Shredder`) which enforces strict limit but gives proper JSON API failure.

This does mean that we won't be usually getting 413 but 200 with error indications, unless exceeding higher limit.
We do need leave that higher limit (I think) for service-protection purposes, although we can definitely tune it appropriately based on what we think makes most sense.
