### ISSUE TITLE
[Vectorize] Add validation for update clause

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#533]
Update clause cannot have updates based on both $vectorize and $vector

**Comment by maheshrajamani** [comment]
@vkarpov15 
`$vectorize` field in the update clause will resolve to `$vector` field. 
In case both field used with same update operator, vectorized value will be used for update. 
If the fields are used in different update operator, existing validation for handling field paths will handle this scenario.

I will close this issue.

**Comment by vkarpov15** [comment]
I think it is worth throwing an error if both `$vectorize` and `$vector` would be updated, because having one overwrite the other automatically is likely to cause confusion.

We've been having a similar issue with a feature we shipped in Mongoose 7.4 that adds an `id` setter which makes `doc.id = '0'.repeat(24)` equivalent to `doc._id = '0'.repeat(24)` by default. Has lead to several issues where users specify both `id` and `_id` because they're assigning Mongoose documents.
