### ISSUE TITLE
Improve max Collection limit verification to be based on available SAIs, not existing Tables

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#608]
(follow-up to #577)

Currently JSON API enforces maximum of 5 (configurable) Collections per-namespace (implemented via #595).

But number of Collections we create is actually limited by number of indexes (SAIs) that can be created.
So we need to check if we could still create enough indexes for a new Collection, not by number of Table that exists, for 2 reasons:

1. Different Collections need different number of Indexes so number of Collections is not necessarily static
2. It may be possible to also create "raw" (non-Collection) tables, and number of indexes those create can be basically anything.

NOTE: to relax SAI count limitation from 50 to 100, we have https://datastax.jira.com/jira/software/c/projects/VECTOR/issues/VECTOR-184

**Comment by jeffreyscarpenter** [comment]
Thinking this through more we probably should support limits on both the number of collections and the number of indexes in order to be the most secure. 

let’s say I already have 47 indexes in my DB but 11 of them are from non-JSON API tables, and 36 of them are from my four JSON API vector collections. I create a new JSON API collection, and I haven’t hit the collection limit yet, but JSON API creates a table and then starts creating the 9 indexes, the 6th index creation is going to fail due to hitting the limit of 50 indexes. This is possible in the current implementation.

The situation we are trying to avoid is this case where we get partially through a createCollection operation and run out of indexes. Because of race conditions around two simultaneous createCollection calls, we may not be able to totally prevent this, but having limits on both number of collections and number of indexes should help reduce occurrence. We will probably also have to implement some kind of rollback behavior that cleans up a partially created collection if there is an index error, and/or provide a utility for operations folks that does this work. This would all be easier if we could wrap a transaction around the table and index creation process.

**Comment by tatu-at-datastax** [comment]
Figuring out which tables are collections and which not is quite complicated and possibly slow, fwtw.
Perhaps we should do this incrementally, starting with index limit, and then improving as needed.

Rollback mechanism can get gnarly too, but I agree something like that would be necessary.
