### ISSUE TITLE
Closing session with possible in-flight queries

### ISSUE THREAD

**Issue by kathirsvn** [stargate/jsonapi#645]
In the native cql driver based implementation, the driver cqlsession object is getting closed on getting evicted from the cache. But there is no check if there are any queries in-flight before closing the session. In other words, is there a graceful close for session?

**Comment by tatu-at-datastax** [comment]
One possibility would be to make closing on expiration delayed by certain amount (15 seconds?). So when "expire-from-cache" is called, actual closing is done from different thread after some delay.
Since connection is no longer accessible via cache, it should drain.

Alternatively we could of course add simple ref counting (keep track of in-flight request count over connection), but if we do that we probably still want some kind of force close after delay in case of stuck requests.
