### ISSUE TITLE
Select Java library for ObjectId generation, decoding

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#921]
To support use of ObjectId as document id, including (but not limited to) auto-generation, we need a Java library for generation and ideally also for decoding (to be able to validate well-formedness) of ObjectId type.

**Comment by clun** [comment]
FYI, Java Clients would probably align with those choices to improve interoperability

**Comment by tatu-at-datastax** [comment]
Looks like there really isn't much choice: mongo java driver appears to be the thing to use:

https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-sync

**Comment by vkarpov15** [comment]
FWIW, the definition of an ObjectId is any 12 bytes. So validation is fairly straightforward depending on what format you use for ObjectIds on the wire. 24 hex chars is the most common.

Generating an ObjectId in the canonical way is also fairly straightforward: https://www.mongodb.com/docs/manual/reference/method/ObjectId/. 4 bytes containing seconds since epoch, 5 bytes random generated once per process, 3 bytes counter that increments on per process basis. Wouldn't be too difficult to implement.

**Comment by tatu-at-datastax** [comment]
Yes, not hard to write but ideally I wouldn't write yet another OSS library (I already maintain `java-uuid-generator`, written in 2003 or so :) )

But fortunately Mongo client has simple `ObjectId` type so I'll probably go with that.

**Comment by tatu-at-datastax** [comment]
Ok, selecting:

* Mongo java client 5.0.0 for `ObjectId` generation, validation: https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-sync/5.0.0
* Java UUID Generator 5.0.0 for UUID generation (supports v1, v4, v6 and v7 unlike JDK `java.util.UUID`: https://mvnrepository.com/artifact/com.fasterxml.uuid/java-uuid-generator/5.0.0

**Comment by tatu-at-datastax** [comment]
Quick update: actually do not need full client package: BSON jar is enough:

* https://mvnrepository.com/artifact/org.mongodb/bson/5.0.0

which is nice as we have much lighter-weight dependency.
